### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/tyto#18]
I started getting a 503 error while running tyto:

```
HTTP Error 503: Service Unavailable
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jakebeal/projects/SBOL/Excel-to-SBOL3/igem_kludge.py", line 63, in <module>
    try: role = tyto.SO.get_uri_by_term(raw_role)
  File "/usr/local/lib/python3.9/site-packages/tyto/owlet.py", line 144, in get_uri_by_term
    response = self._query(query, error_msg)[0]
  File "/usr/local/lib/python3.9/site-packages/tyto/owlet.py", line 56, in _query
    response = Ontology._convert_ontobee_response(response)
  File "/usr/local/lib/python3.9/site-packages/tyto/owlet.py", line 87, in _convert_ontobee_response
    response = response.convert()  # Convert http response to JSON
AttributeError: 'list' object has no attribute 'convert'
```

I think the service it's hitting when dealing with a bad name might have started rejecting queries (too many too quickly?), and TYTO isn't handling this gracefully.

**Comment by jakebeal** [comment]
This might have happened due to running too many queries, so should happen less often now that caching exists.

Recommended resolution: raise a more appropriate and informative error.

**Comment by jakebeal** [comment]
Closing until reproduced.
